kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: gyazo
  labels:
    app: gyazo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gyazo
  template:
    metadata:
      labels:
        app: gyazo
    spec:
      containers:
        - name: gyazo
          image: docker.pkg.github.com/imhugofonseca/gyazo/gyazo
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
          env:
          - name: BKT_HOST  
            value: "fra1.digitaloceanspaces.com"
          - name: BKT_SPACE_DOMAIN  
            value: "img.hugo.gg"
          - name: BKT_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: gyazo-do-keys
                key: DO_ACCESS_KEY
          - name: BKT_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: gyazo-do-keys
                key: DO_SECRET_ACCESS_KEY
      imagePullSecrets:
        - name: github-registry
      
---
apiVersion: v1
kind: Service
metadata:
  name: gyazo
  namespace: default
  labels:
    app: gyazo
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: gyazo
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gyazo-route
  namespace: default
  labels:
    app: gyazo
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`upload.img.hugo.gg`)
    kind: Rule
    services:
    - name: gyazo
      port: 80
  