apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyazo
spec:
  selector:
    matchLabels:
      app: gyazo
  template:
    metadata:
      labels:
        app: gyazo
    spec:
      containers:
      - name: gyazo
        image: registry.gitlab.com/hugofonseca/gyazo
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: gayzo
spec:
  selector:
    app: gayzo
  ports:
  - port: 80
    targetPort: 80
---
